# Issues/PRs with no activity for a year will be marked as stale
daysUntilStale: 365

# If no one has replied inside a week after an issue is marked stale, close it.
daysUntilClose: 7

staleLabel: wontfix
markComment: >
  This issue or PR has been automatically marked as stale because there has been
  no activity in over a year. It will be closed in 1 week if no further activity occurs.
  Thanks for your contribution, and please don't hesitate to comment if this issue/PR
  is still relevant.
exemptLabels:
  - pinned
  - security
